repos:
-   repo: https://github.com/PyCQA/isort
    rev: '5.13.2'  # Specify a version
    hooks:
    -   id: isort
-   repo: https://github.com/psf/black
    rev: '23.12.1'  # Specify a version
    hooks:
    -   id: black
-   repo: https://github.com/PyCQA/flake8
    rev: '7.0.0'  # Specify a version
    hooks:
    -   id: flake8
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.8.0'  # Specify a version
    hooks:
    -   id: mypy
